name: habit_level_up
description: Habit Level Up Flutter application
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.2
  
  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  
  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  
  # Backend & Environment
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.1.0
  
  # Local packages
  domain:
    path: packages/domain
  data_local:
    path: packages/data_local

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1

  path: any
flutter:
  uses-material-design: true
  
  assets:
    - .env