name: habit_level_up
description: Habit Level Up Flutter application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.2
  
  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  
  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  
  # Local SQLite Database
  sqflite: ^2.3.0
  uuid: ^4.4.0
  
  # State management & async
  rxdart: ^0.27.7
  
  # Password hashing
  crypto: ^3.0.3
  
  # Routing
  go_router: ^14.6.2
  
  # Calendar
  table_calendar: ^3.1.2
  
  # Local packages
  domain:
    path: packages/domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1
  
  # Testing
  mockito: ^5.4.4
  sqflite_common_ffi: ^2.3.0
  
  # Workspace management
  melos: ^6.0.0

  path: any
flutter:
  uses-material-design: true
  
  # No assets needed for offline app