name: data_local
description: Local data persistence with Isar for habit tracking
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  domain:
    path: ../domain
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  test: ^1.25.8
  mocktail: ^1.0.4