name: domain
description: Pure Dart domain layer for habit tracking
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  meta: ^1.15.0
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  test: ^1.25.8
  mocktail: ^1.0.4